kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: test
    image: node:12
    commands:
      - npm run test
    depends_on: [install_dependencies]
  - name: generate changelog
    image: node:12
    commands:
      - npx semantic-release
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    depends_on: [test]
    when:
      branch: master
      event: push
  - name: docker
    image: banzaicloud/drone-kaniko
    settings:
      email: jeremy.chauvin@systeme-u.fr
      dockerfile: ./Dockerfile
      registry: docker.pkg.github.com
      repo: singebob/bot-projet-mspr/api
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      tags:
        - ${DRONE_TAG}
        - latest
    depends_on: [test]
    when:
      event: tag
  - name: deploy
    image: node:12
    commands:
      - npm install -g caprover
      - caprover deploy -h ${DOMAIN} -p ${PASSWORD} -b master -a ${APPNAME}
    environment:
      DOMAIN:
        from_secret: DOMAIN
      PASSWORD:
        from_secret: PASSWORD
      APPNAME:
        from_secret: APPNAME
    depends_on: [docker]
    when:
      event: tag
